import type { Metadata } from "next";
import { Aboreto } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import ModalProvider from "@/providers/ModalProvider";
import ToastProvider from "@/providers/ToastProvider";

const font = Aboreto({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Illuminia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ModalProvider />
        <ToastProvider />
        <Navbar />
        <main>{children}</main>
        <br />
        <br />
        <Footer />
      </body>
    </html>
  );
}
